<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class AccountVerification extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'new_email',
        'token',
        'expired_at',
        'status',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'expired_at' => 'datetime',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (AccountVerification $accountVerification) {
            $accountVerification->slug = Str::uuid()->toString();
        });

        static::created(function (AccountVerification $accountVerification) {
            self::where('user_id', $accountVerification->user_id)
                ->where('id', '!=', $accountVerification->id)
                ->delete();
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function scopeUserId(Builder $query, $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    public function scopeFilterByStatus(Builder $query, $status): Builder
    {
        return $query->where('status', $status);
    }
}
