<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Application extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'name',
        'description',
        'website',
        'main_website',
        'register_verification',
        'notification_method'
    ];

    protected function casts(): array
    {
        return [
            'register_verification' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Application $application) {
            $application->slug = Str::uuid()->toString();
        });
    }
}
