<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class ClassLevel extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'registration_category_id',
        'code',
        'name',
        'is_active'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (ClassLevel $classLevel) {
            $classLevel->slug = Str::uuid()->toString();
            $classLevel->code = strtoupper(Str::slug($classLevel->name));
        });

        static::updating(function (ClassLevel $classLevel) {
            $classLevel->code = strtoupper(Str::slug($classLevel->name));
        });
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    public function registrationCategory(): BelongsTo
    {
        return $this->belongsTo(RegistrationCategory::class);
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    public function scopeEducationalInstitutionId(Builder $query, $educationalInstitutionId): Builder
    {
        return $query->where('educational_institution_id', $educationalInstitutionId);
    }

    public function scopeRegistrationCategoryId(Builder $query, $registrationCategoryId): Builder
    {
        return $query->where('registration_category_id', $registrationCategoryId);
    }
}
