<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ClassLevel extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'registration_category_id',
        'code',
        'name',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (ClassLevel $classLevel) {
            $classLevel->slug = Str::uuid()->toString();
            $classLevel->code = strtoupper(Str::slug($classLevel->name));
        });

        static::updating(function (ClassLevel $classLevel) {
            $classLevel->code = strtoupper(Str::slug($classLevel->name));
        });
    }
}
