<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class DetailMediaFile extends Model
{
    protected $fillable = [
        'slug',
        'media_file_id',
        'educational_institution_id',
        'registration_path_id',
    ];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (DetailMediaFile $detailMediaFile) {
            $detailMediaFile->slug = Str::uuid()->toString();
        });
    }

    public function mediaFile(): BelongsTo
    {
        return $this->belongsTo(MediaFile::class);
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    public function registrationPath(): BelongsTo
    {
        return $this->belongsTo(RegistrationPath::class);
    }
}
