<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class EducationalInstitution extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'educational_level_id',
        'name',
        'email',
        'website',
        'province',
        'city',
        'district',
        'village',
        'street',
        'postal_code',
        'profile',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (EducationalInstitution $educationalInstitution) {
            $educationalInstitution->slug = Str::uuid()->toString();
        });
    }

    public function educationalLevel(): BelongsTo
    {
        return $this->belongsTo(EducationalLevel::class);
    }

    public function registrationScheduleActive(): HasOne
    {
        return $this->hasOne(RegistrationSchedule::class, 'educational_institution_id')
            ->whereHas('schoolYear', function ($query) {
                $query->where('is_active', true);
            });
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }
}
