<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class EmailChange extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'new_email',
        'token',
        'expired_at',
        'status',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'expired_at' => 'datetime',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (EmailChange $emailChange) {
            $emailChange->slug = Str::uuid()->toString();
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
