<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class EmailConfig extends Model
{
    protected $fillable = [
        'slug',
        'mail_username',
        'mail_password_app',
        'is_active'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (EmailConfig $emailConfig) {
            $emailConfig->slug = Str::uuid()->toString();
        });
    }
}
