<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class FaqCategory extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'qualification'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'qualification' => 'array'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (FaqCategory $faqCategory) {
            $faqCategory->slug = Str::uuid()->toString();
        });
    }

    public function faqs(): HasMany
    {
        return $this->hasMany(Faq::class, 'faq_category_id');
    }

    // TODO SCOPE
    public function scopeFilterBySlug(Builder $query, $slug): Builder
    {
        return $query->where('slug', $slug);
    }
}
