<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Lesson extends Model
{
    protected $fillable = [
        'slug',
        'code',
        'name',
        'type',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Lesson $lesson) {
            $lesson->slug = Str::uuid()->toString();
        });
    }

    public function lessonMappings(): HasMany
    {
        return $this->hasMany(LessonMapping::class, 'lesson_id');
    }

    // TODO Scope
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }
}
