<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class LessonMapping extends Model
{
    protected $fillable = [
        'slug',
        'lesson_id',
        'educational_institution_id',
        'previous_educational_group',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'previous_educational_group' => 'array',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (LessonMapping $lessonMapping) {
            $lessonMapping->slug = Str::uuid()->toString();
        });
    }

    public function lesson(): BelongsTo
    {
        return $this->belongsTo(Lesson::class);
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    // TODO Scope
    public function scopeFilterData(Builder $query, $filter): Builder
    {
        return $query->where([
            'lesson_id' => $filter['lesson_id'],
            'educational_institution_id' => $filter['educational_institution_id']
        ]);
    }

    public function scopeEducationalInstitutionId(Builder $query, $educationalInstitutionId): Builder
    {
        return $query->where('educational_institution_id', $educationalInstitutionId);
    }
}
