<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class LessonMapping extends Model
{
    protected $fillable = [
        'slug',
        'lesson_id',
        'educational_institution_id',
        'previous_educational_group',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'previous_educational_group' => 'array',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (LessonMapping $lessonMapping) {
            $lessonMapping->slug = Str::uuid()->toString();
        });
    }
}
