<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class Major extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'code',
        'name',
        'is_active'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Major $major) {
            $major->slug = Str::uuid()->toString();
            $major->code = strtoupper(Str::slug($major->name));
        });

        static::created(function (Major $major) {
            self::where([
                'educational_institution_id' => $major->educational_institution_id,
                'code' => $major->code
            ])
                ->where('id', '!=', $major->id)
                ->update(['is_active' => false]);
        });

        static::updating(function (Major $major) {
            $major->code = strtoupper(Str::slug($major->name));
        });

        static::updated(function (Major $major) {
            self::where([
                'educational_institution_id' => $major->educational_institution_id,
                'code' => $major->code
            ])
                ->where('id', '!=', $major->id)
                ->update(['is_active' => false]);
        });
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    public function scopeEducationalInstitutionId(Builder $query, $educationalInstitutionId): Builder
    {
        return $query->where('educational_institution_id', $educationalInstitutionId);
    }
}
