<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MediaFile extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'file_code',
        'category',
        'educational_institutions',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'educational_institutions' => 'array'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MediaFile $uploadFile) {
            $uploadFile->slug = Str::uuid()->toString();
            $uploadFile->file_code = Str::slug($uploadFile->name);
        });

        static::updating(function (MediaFile $uploadFile) {
            $uploadFile->file_code = Str::slug($uploadFile->name);
        });
    }
}
