<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;

class MessageTemplate extends Model
{
    protected $fillable = [
        'slug',
        'title',
        'educational_institution_id',
        'category',
        'recipient',
        'message',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MessageTemplate $messageTemplate) {
            $messageTemplate->slug = Str::uuid()->toString();
        });

        static::created(function (MessageTemplate $messageTemplate) {
            self::where([
                'educational_institution_id' => $messageTemplate->educational_institution_id,
                'category' => $messageTemplate->category,
                'recipient' => $messageTemplate->recipient
            ])
                ->where('id', '!=', $messageTemplate->id)
                ->update(['is_active' => false]);
        });

        static::updated(function (MessageTemplate $messageTemplate) {
            self::where([
                'educational_institution_id' => $messageTemplate->educational_institution_id,
                'category' => $messageTemplate->category,
                'recipient' => $messageTemplate->recipient
            ])
                ->where('id', '!=', $messageTemplate->id)
                ->update(['is_active' => false]);
        });
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    public function messageReceiver(): HasOne
    {
        return $this->hasOne(MessageReceiver::class, 'message_template_id');
    }

    // TODO Scope
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    public function scopeEducationalInstitutionId(Builder $query, $educationalInstitutionId): Builder
    {
        return $query->where('educational_institution_id', $educationalInstitutionId);
    }

    public function scopeFilterByCategory(Builder $query, $category): Builder
    {
        return $query->where('category', $category);
    }

    public function scopeFilterByRecipient(Builder $query, $recipient): Builder
    {
        return $query->where('recipient', $recipient);
    }

    public function scopeFilterByEducationalInstitution(Builder $query): Builder
    {
        $auth = auth()->user();

        return $query->when(!$auth->hasRole('super-admin'), fn($query) => $query->where('educational_institution_id'), optional(optional($auth)->admin)->educational_institution_id);
    }
}
