<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class MessageTemplate extends Model
{
    protected $fillable = [
        'slug',
        'title',
        'educational_institution_id',
        'category',
        'recipient',
        'message',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MessageTemplate $messageTemplate) {
            $messageTemplate->slug = Str::uuid()->toString();
        });

        static::created(function (MessageTemplate $messageTemplate) {
            self::where([
                'educational_institution_id' => $messageTemplate->educational_institution_id,
                'category' => $messageTemplate->category,
                'recipient' => $messageTemplate->recipient
            ])
                ->where('id', '!=', $messageTemplate->id)
                ->update(['is_active' => false]);
        });

        static::updated(function (MessageTemplate $messageTemplate) {
            self::where([
                'educational_institution_id' => $messageTemplate->educational_institution_id,
                'category' => $messageTemplate->category,
                'recipient' => $messageTemplate->recipient
            ])
                ->where('id', '!=', $messageTemplate->id)
                ->update(['is_active' => false]);
        });
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }
}
