<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MessageTemplate extends Model
{
    protected $fillable = [
        'slug',
        'title',
        'educational_institution_id',
        'category',
        'message',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MessageTemplate $messageTemplate) {
            $messageTemplate->slug = Str::uuid()->toString();
        });
    }
}
