<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PaymentTransaction extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'registration_fee_id',
        'amount',
        'paid_amount',
        'paid_rest',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PaymentTransaction $paymentTransaction) {
            $paymentTransaction->slug = Str::uuid()->toString();
        });
    }
}
