<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PaymentChannel extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'code',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PaymentChannel $paymentChannel) {
            $paymentChannel->slug = Str::uuid()->toString();
        });
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    public static function findByCode($code): PaymentChannel
    {
        return self::where('code', $code)->firstOrFail();
    }
}
