<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Payment extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'serial_number',
        'code',
        'user_id',
        'amount',
        'checkout_link',
        'status',
        'payment_method',
        'payment_channel',
        'bank_account_id',
        'expires_at',
        'paid_at'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'expires_at' => 'timestamp',
            'paid_at' => 'timestamp'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Payment $payment) {
            $payment->slug = Str::uuid()->toString();
            $payment->serial_number = self::max('serial_number') + 1;
            $payment->code = 'INV' . Str::padLeft($payment->serial_number, 4, '0');
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function paymentTransactions(): HasMany
    {
        return $this->hasMany(PaymentTransaction::class, 'payment_id');
    }

    public function bankAccount(): BelongsTo
    {
        return $this->belongsTo(BankAccount::class);
    }
}
