<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class PaymentTransaction extends Model
{
    protected $fillable = [
        'slug',
        'payment_id',
        'registration_fee_id',
        'amount',
        'paid_amount',
        'paid_rest',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PaymentTransaction $paymentTransaction) {
            $paymentTransaction->slug = Str::uuid()->toString();
        });
    }

    public function payment(): BelongsTo
    {
        return $this->belongsTo(Payment::class);
    }

    // TODO Scope
    public function scopeRegistrationFeeId(Builder $query, $registrationFeeId): Builder
    {
        return $query->where('registration_fee_id', $registrationFeeId);
    }
}
