<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class PaymentSetting extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'payment_method',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PaymentSetting $paymentSetting) {
            $paymentSetting->slug = Str::uuid()->toString();
        });
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    public function scopeEducationalInstitutionId(Builder $query, $educationalInstitutionId): Builder
    {
        return $query->where('educational_institution_id', $educationalInstitutionId);
    }
}
