<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PersonalData extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'place_of_birth',
        'date_of_birth',
        'gender',
        'child_to',
        'number_of_brothers',
        'family_relationship',
        'religion',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'date_of_birth' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PersonalData $personalData) {
            $personalData->slug = Str::uuid()->toString();
        });
    }

    public function scopeUserId(Builder $query, $userId): Builder
    {
        return $query->where('user_id', $userId);
    }
}
