<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PreviousSchool extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'school_name',
        'educational_group_id',
        'status',
        'province',
        'city',
        'district',
        'village',
        'street'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PreviousSchool $previousSchool) {
            $previousSchool->slug = Str::uuid()->toString();
        });
    }

    // TODO Scope
    public function scopeUserId(Builder $query, $userId): Builder
    {
        return $query->where('user_id', $userId);
    }
}
