<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class PreviousSchoolReference extends Model
{
    protected $fillable = [
        'slug',
        'educational_group_id',
        'npsn',
        'name',
        'province',
        'city',
        'district',
        'village',
        'street',
        'status',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (PreviousSchoolReference $previousSchoolReference) {
            $previousSchoolReference->slug = Str::uuid()->toString();
        });
    }

    public function educationalGroup(): BelongsTo
    {
        return $this->belongsTo(EducationalGroup::class);
    }

    // TODO Scope
    public function scopeEducationalGroupId(Builder $query, $educationalGroupId): Builder
    {
        return $query->where('educational_group_id', $educationalGroupId);
    }
}
