<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Profession extends Model
{
    protected $fillable = [
        'slug',
        'name',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Profession $profession) {
            $profession->slug = Str::uuid()->toString();
        });
    }

    public function fatherProfessions(): HasMany
    {
        return $this->hasMany(Family::class, 'father_profession_id');
    }

    public function motherProfessions(): HasMany
    {
        return $this->hasMany(Family::class, 'mother_profession_id');
    }

    public function guardianProfessions(): HasMany
    {
        return $this->hasMany(Family::class, 'guardian_profession_id');
    }
}
