<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class RegistrationPath extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'code',
        'name',
        'is_active'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (RegistrationPath $registrationPath) {
            $registrationPath->slug = Str::uuid()->toString();
            $registrationPath->code = strtoupper(Str::slug($registrationPath->name));
        });

        static::updating(function (RegistrationPath $registrationPath) {
            $registrationPath->code = strtoupper(Str::slug($registrationPath->name));
        });
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }
}
