<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class RegistrationSchedule extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'school_year_id',
        'start_date',
        'end_date',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'start_date' => 'date',
            'end_date' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (RegistrationSchedule $registrationSchedule) {
            $registrationSchedule->slug = Str::uuid()->toString();
        });
    }
}
