<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class RegistrationSchedule extends Model
{
    protected $fillable = [
        'slug',
        'educational_institution_id',
        'school_year_id',
        'start_date',
        'end_date',
        'quota',
        'remaining_quota'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'start_date' => 'date',
            'end_date' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (RegistrationSchedule $registrationSchedule) {
            $registrationSchedule->slug = Str::uuid()->toString();
        });
    }

    public function schoolYear(): BelongsTo
    {
        return $this->belongsTo(SchoolYear::class);
    }

    public function educationalInstitution(): BelongsTo
    {
        return $this->belongsTo(EducationalInstitution::class);
    }

    // TODO Scope
    public function scopeFilterData(Builder $query, $filter): Builder
    {
        return $query->where([
            'educational_institution_id' => $filter['educational_institution_id'],
            'school_year_id' => $filter['school_year_id']
        ]);
    }

    public function scopeFilterByEducationalInstitution(Builder $query): Builder
    {
        $auth = auth()->user();

        return $query->when(!$auth->hasRole('super-admin'), fn($query) => $query->where('educational_institution_id'), optional(optional($auth)->admin)->educational_institution_id);
    }
}
