<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class SchoolReport extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'user_id',
        'semester',
        'total_score',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (SchoolReport $schoolReport) {
            $schoolReport->slug = Str::uuid()->toString();
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    // TODO Scope
    public function scopeFilterData(Builder $query, $filter): Builder
    {
        return $query->where([
            'user_id' => $filter['user_id'],
            'semester' => $filter['semester']
        ]);
    }

    public function scopeFilterBySlug(Builder $query, $slug): Builder
    {
        return $query->where('slug', $slug);
    }
}
