<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class SchoolReport extends Model
{
    protected $fillable = [
        'slug',
        'user_id',
        'total_score',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (SchoolReport $schoolReport) {
            $schoolReport->slug = Str::uuid()->toString();
        });
    }
}
